logging:
  config: classpath:logback-spring-prod.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/squirrel_shop?serverTimezone=GMT%2b8
    username: root
    password: 12345678
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true